classdef NameGenerator < handle
    %NAMEGEERATOR Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        taskNames = {'Flat Sleep', 'Economic Motion', ...
            'Unwritten Experience', 'Noiseless Stone', ...
            'Impolite Heat', 'Arrogant Flame', 'Staking System', ...
            'Towering Test', 'Alert Burst', 'Thinkable Ink', ...
            'Better Behavior', 'Hallowed Sign',  'Befitting Plant', ...
            'Absorbed Copper', 'Husky Verse', 'Chief Government', ...
            'Chemical Rhythm', 'Onerous Effect', 'Wistful Act', ...
            'Wide Growth', 'Muddled Reward', 'Brainy Damage', ...
            'Murky Mass',  'Silky Waste', 'Incompetent Secretary', ...
            'Hard Development', 'Crabby Example', 'Illustrious Balance', ...
            'Statuesque Name', 'Breezy Rain'};
%         inputNames = {'Edge', 'Tender', 'Engine', 'Loss', 'Ego', ...
%             'Feeling', 'Print', 'Division', 'Waste', 'Distribution', ...
%             'Point', 'Government', 'System', 'Start', 'Warranty', ...
%             'Sleep', 'Motion', 'Experience', 'Stone', 'Heat', 'Flame', ...
%             'Back', 'Test', 'Burst', 'Ink', 'Behavior', 'Sign', ...
%             'Plant', 'Copper', 'Verse', 'Work', 'Rhythm', 'Effect', ...
%             'Awareness', 'Growth', 'Reward', 'Damage', 'Mass', 'Self', ...
%             'Estate', 'Development', 'Example', 'Balance', 'Name', ...
%             'Rain', 'Blood', 'License', 'Zoom', 'Importance', ...
%             'Breach', 'Bang', 'Chord', 'Butter', 'Attempt', 'Animal', ...
%             'Observation', 'Steam', 'Fear', 'Cotton', 'Lift', 'Owner', ...
%             'Shock', 'Reaction', 'Family', 'Company', 'Smell', 'Sand', ...
%             'Stitch', 'Current', 'Snow', 'List', 'Digestion', ...
%             'Amusement', 'Machine', 'Knowledge', 'Reading', 'Swim', ...
%             'Vessel', 'Meal', 'Answer', 'Request', 'Man', 'Harbor', ...
%             'Paint', 'Religion', 'Comparison', 'Science', 'Judge', ...
%             'Story', 'Group', 'Teaching', 'Friend', 'Wind', 'Money', ...
%             'Trade', 'Paper', 'Woman', 'Amount', 'Turn', 'Shade', ...
%             'Flight', 'Ray', 'Committee', 'Mountain', 'Offer', 'Base', ...
%             'Flower', 'Crack', 'Revenue', 'Weight', 'Summer', 'River', ...
%             'Tin', 'Platform', 'Script', 'Nation', 'Shake', ...
%             'Invention', 'Room', 'Hope', 'Driving', 'Preference', ...
%             'Rant', 'Size', 'Meeting', 'Oil', 'Letter', 'Scale', ...
%             'Substance', 'Variety', 'Use', 'Move', 'Ratio', 'Respect', ...
%             'Biological', 'Price', 'Play', 'Help', 'Event', 'Need', ...
%             'Slope', 'Theory', 'Agreement', 'Word', 'Sneeze', ...
%             'Winter', 'Brother', 'Poison', 'Mark', 'Coverage'};
%         outputNames = {'Sentient', 'Pale', 'Irrational', 'Crucial', ...
%             'Untidy', 'Mixed', 'Adaptable', 'Exotic', 'Cheerful', ...
%             'Lowly', 'Hypnotic', 'Berserk', 'Ancient', 'Delightful', ...
%             'Intelligent', 'Round', 'Profuse', 'Impartial', 'Tame', ...
%             'Makeshift', 'Similar', 'Hard', 'Erratic', 'Clean', ...
%             'Groovy', 'Fragile', 'Strange', 'Lopsided', 'Repulsive', ...
%             'Harsh', 'Lumpy', 'Terrific', 'Uniform', 'Keen', ...
%             'Unequaled', 'Big', 'Nervous', 'Chaotic', 'Consistent', ...
%             'Responsible', 'Able', 'Descriptive', 'Tricky', 'Flexible', ...
%             'Decisive', 'Survivable', 'Confusing', 'Detailed', ...
%             'Graphic', 'Light', 'Unhappy', 'Misleading', 'Spectacular', ...
%             'Used', 'Condemned', 'Young', 'Central', 'Striped', ...
%             'Spooky', 'Remarkable', 'Stormy', 'Amazing', 'Powerful', ...
%             'Defined', 'Stingy', 'Apathetic', 'Wasteful', 'Absorbant', ...
%             'Complete', 'Upset', 'Bright', 'Wiry', 'Subdued', ...
%             'Mysterious', 'Yielding', 'Nebulous', 'Living', 'Thick', ...
%             'Hidden', 'Cold', 'Small', 'Independent', 'Raspy', ...
%             'Protected', 'Huge', 'Cuddly', 'Sudden', 'Helpful', ...
%             'Slimy', 'Perfect', 'Illegal', 'Normal', 'Smart', 'Watery', ...
%             'Unruly', 'Meaty', 'Special', 'Explicit', 'Colorful', ...
%             'Boiling', 'Vigorous', 'Roasted', 'Tan', 'Curious', ...
%             'Resonant', 'Ahead', 'Vast', 'Defective', 'Precious', ...
%             'Tired', 'Successful', 'Senior', 'Unique', 'Tight', ...
%             'Giant', 'Lean', 'Brief', 'Fumbling', 'Hanging', 'Sloppy', ...
%             'Hissing', 'Adhesive', 'Squealing', 'Amusing', 'Busy', ...
%             'Isolating', 'Spotty', 'Petite', 'Right', 'Loud', 'Stale', ...
%             'Grateful', 'Minor', 'Womanly', 'Abrupt', 'Soft', ...
%             'Stereotyped', 'Wandering', 'Ripe', 'Spicy', 'Prompt', ...
%             'Black', 'Apart', 'Near', 'Fun', 'Easy', 'Wrong', 'Rare', ...
%             'Crooked', 'Guarded', };
        inputNames = {'Size', 'Capacity', 'Mass', 'Volume', 'Power', ...
            'Speed', 'Temperature', 'Diameter', 'Length', ...
            'Shielding', 'Insulation', 'Flux', 'Resistance', ...
            'Stability', 'Voltage', 'Flexibility', 'Stiffness', ...
            'Torque', 'Acceleration'};
%         outputNames = {'Flexibility', 'Cost', 'Value', 'Adaptability', ...
%             'Sustainability', 'Performance', 'Revenue', 'Modularity', ...
%             'Delay', 'Repairability'};
        outputNames = {'Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon', ...
            'Zeta', 'Theta', 'Iota', 'Kappa', 'Mu', 'Omicron', 'Pi', ...
            'Rho', 'Sigma', 'Tau', 'Psi', 'Omega'};
        taskCounter = 1;
        inputCounter = 1;
        outputCounter = 1;
    end
    
    methods
        function obj = NameGenerator()
            obj.taskNames = obj.taskNames(randperm(length(obj.taskNames)));
            obj.inputNames = obj.inputNames(randperm(length(obj.inputNames)));
            obj.outputNames = obj.outputNames(randperm(length(obj.outputNames)));
        end
        function name = getTaskName(obj)
            name = obj.taskNames{obj.taskCounter};
            obj.taskCounter = mod(obj.taskCounter, ...
                length(obj.taskNames)) + 1;
        end
        function names = getInputNames(obj, number)
            names = cell(number, 1);
            for i=1:number
               names{i} = obj.inputNames{obj.inputCounter};
                obj.inputCounter = mod(obj.inputCounter, ...
                    length(obj.inputNames)) + 1;
            end
        end
        function names = getOutputNames(obj, number)
            names = cell(number, 1);
            for i=1:number
               names{i} = obj.outputNames{obj.outputCounter};
                obj.outputCounter = mod(obj.outputCounter, ...
                    length(obj.outputNames)) + 1;
            end
        end
    end
    
end

